const automatedTestWebsiteSample = {
	"sheet": {
		"sheetId": "11-aa_N0bnlejes3PdjYl5tZrKryVe5n4dNKSMqQ7i00",
		"sheetName": "Sajid: MVS Events Tenant(Full)",
		"pageId": "226939388",
		"pageName": "FrameWork-Test-Website"
	},
	"configurations": [{
		"command": "Environment",
		"key": "Environment",
		"value": "qa"
	}, {
		"command": "qa",
		"key": "fname",
		"value": "subash poudel"
	}, {
		"command": "dev",
		"key": "fname",
		"value": "sanjay"
	}],
	"reusables": [{
		"functionName": "Fill Service Selection Page",
		"parameter": "//*[@data-qa=\"service-selection\"]/option[5]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Service Selection Page",
		"parameter": "//*[@data-qa=\"vaccine-selection\"]/option[2]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Service Selection Page",
		"parameter": "//*[@data-qa=\"select-clinic-button\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Location Selection Page",
		"parameter": "//*[@data-qa=\"location-clinic-card-1\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Location Selection Page",
		"parameter": "//*[@data-qa=\"continue\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Eligibility Questions Page",
		"parameter": "//*[@data-qa=\"patient-eligibility-firstName\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Eligibility Questions Page",
		"parameter": "Sajid",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Eligibility Questions Page",
		"parameter": "//*[@data-qa=\"patient-eligibility-lastName\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Eligibility Questions Page",
		"parameter": "Ansari",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Eligibility Questions Page",
		"parameter": "//*[@data-qa=\"patient-eligibility-terms-condition-check\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Eligibility Questions Page",
		"parameter": "//*[@data-qa=\"patient-eligibility-continue-button\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Health Screening Page",
		"parameter": "//*[@data-qa=\"health-screening-terms-condition-check\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Health Screening Page",
		"parameter": "//*[@data-qa=\"health-screening-continue-button\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-birthYear\"]/option[26]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-birthMonth\"]/option[13]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-birthDay\"]/option[16]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-ethnicity\"]/option[2]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-race\"]/option[2]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-gender\"]/option[2]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-primaryLanguage\"]/option[8]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-mobileNumber\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "9860789006",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-emailAddress\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "sajidansari33272@gmail.com",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-emailAddressConfirm\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "sajidansari33272@gmail.com",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-referringOrganization\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "Leapfrog Technology",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-notificationConsent\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-homeAddress\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "Central Road",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-city\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "Seattle",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-state\"]/option[16]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-zipCode\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "98101",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-dyn-target-name=\"data-qa-patient-info-terms-and-condition\"]",
		"parameterType": "XPath",
		"command": "MultiRun",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-signature-add\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-signature-canvas-container\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "//*[@data-qa=\"patient-info-select-clinic-and-time-button\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Patient Info",
		"parameter": "5",
		"parameterType": "Seconds",
		"command": "Wait.Until",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Schedule Appointment",
		"parameter": "//*[@data-qa=\"continue-to-confirmation-page-button\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Confirmation Page",
		"parameter": "8",
		"parameterType": "Seconds",
		"command": "Wait.Until",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Confirmation Page",
		"parameter": "const elem = document.evaluate('//*[@id=\"recaptcha-anchor\"]/div[1]', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;\nconsole.log(elem);\nconsole.log('elem is null', elem === null);\nif(elem) {\nelem.click();\n}",
		"parameterType": "",
		"command": "Javascript",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Confirmation Page",
		"parameter": "const elem = document.evaluate('//*[@id=\"root\"]/div/div[2]/div/section[1]/section/div[2]/div[2]', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;\nconsole.log(elem);\nconsole.log('elem is null', elem === null);\nif(elem) {\nelem.click();\n}",
		"parameterType": "",
		"command": "Javascript",
		"expectedResult": "//*[@id=\"root\"]/div/div[2]/div/section[1]/section/div[2]/div[2]",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Confirmation Page",
		"parameter": "4",
		"parameterType": "Seconds",
		"command": "Wait.Until",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Confirmation Page",
		"parameter": "//*[@data-qa=\"confirm-and-submit-button\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Confirmation Page",
		"parameter": "20",
		"parameterType": "Seconds",
		"command": "Wait.Until",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}, {
		"functionName": "Fill Confirmation Page",
		"parameter": "21",
		"parameterType": "Seconds",
		"command": "Wait.Until",
		"expectedResult": "",
		"rowNumber": -1,
		"testCaseId": "N/A",
		"step": "N/A",
		"label": "N/A"
	}],
	"testcases": [{
		"rowNumber": 2,
		"parameter": "http://192.168.1.168:5500/frameworkTestWebsite/index.html?#",
		"parameterType": "",
		"command": "Visit",
		"expectedResult": ""
	}, {
		"rowNumber": 3,
		"parameter": 15,
		"parameterType": "Seconds",
		"command": "Wait.Until",
		"expectedResult": ""
	}, {
		"rowNumber": 4,
		"parameter": "//*[@data-qa=\"basic-firstName\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": ""
	}, {
		"rowNumber": 5,
		"parameter": "Sajid",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": ""
	}, {
		"rowNumber": 6,
		"parameter": "//*[@data-qa=\"basic-middleName\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": ""
	}, {
		"rowNumber": 7,
		"parameter": "Ansari",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": ""
	}, {
		"rowNumber": 8,
		"parameter": "//*[@data-qa=\"basic-lastName\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": ""
	}, {
		"rowNumber": 9,
		"parameter": "Ansari",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": ""
	}, {
		"rowNumber": 10,
		"parameter": "//*[@data-qa=\"basic-next-button\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": ""
	}, {
		"rowNumber": 11,
		"parameter": "2",
		"parameterType": "Seconds",
		"command": "Wait.Until",
		"expectedResult": ""
	}, {
		"rowNumber": 12,
		"parameter": "//*[@data-qa=\"contact-emailAddress\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": ""
	}, {
		"rowNumber": 13,
		"parameter": "sajidansari33272@gmail.com",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": ""
	}, {
		"rowNumber": 14,
		"parameter": "//*[@data-qa=\"contact-homeAddress\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": ""
	}, {
		"rowNumber": 15,
		"parameter": "Kathmandu",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": ""
	}, {
		"rowNumber": 16,
		"parameter": "//*[@data-qa=\"contact-phoneNumber\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": ""
	}, {
		"rowNumber": 17,
		"parameter": "9817253327",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": ""
	}, {
		"rowNumber": 18,
		"parameter": "//*[@data-qa=\"contact-next-button\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": ""
	}, {
		"rowNumber": 19,
		"parameter": "2",
		"parameterType": "Seconds",
		"command": "Wait.Until",
		"expectedResult": ""
	}, {
		"rowNumber": 20,
		"parameter": "//*[@data-qa=\"dob-year\"]/option[5]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": ""
	}, {
		"rowNumber": 21,
		"parameter": "//*[@data-qa=\"dob-month\"]/option[6]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": ""
	}, {
		"rowNumber": 22,
		"parameter": "//*[@data-qa=\"dob-day\"]/option[24]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": ""
	}, {
		"rowNumber": 23,
		"parameter": "//*[@data-qa=\"dob-gender\"]/option[2]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": ""
	}, {
		"rowNumber": 24,
		"parameter": "//*[@data-qa=\"dob-previous-next-button\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": ""
	}, {
		"rowNumber": 25,
		"parameter": "2",
		"parameterType": "Seconds",
		"command": "Wait.Until",
		"expectedResult": ""
	}, {
		"rowNumber": 26,
		"parameter": "//*[@data-qa=\"login-username\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": ""
	}, {
		"rowNumber": 27,
		"parameter": "Sajid Asanri",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": ""
	}, {
		"rowNumber": 28,
		"parameter": "//*[@data-qa=\"login-password\"]",
		"parameterType": "XPath",
		"command": "Select",
		"expectedResult": ""
	}, {
		"rowNumber": 29,
		"parameter": "9817253327",
		"parameterType": "Text",
		"command": "Type",
		"expectedResult": ""
	}, {
		"rowNumber": 30,
		"parameter": "//*[@data-dyn-target-name=\"data-qa-login-term-condition\"]",
		"parameterType": "XPath",
		"command": "MultiRun",
		"expectedResult": ""
	}, {
		"rowNumber": 31,
		"parameter": "//*[@data-qa=\"login-submit-button\"]",
		"parameterType": "XPath",
		"command": "Click",
		"expectedResult": ""
	}, {
		"rowNumber": 32,
		"parameter": 5,
		"parameterType": "Seconds",
		"command": "Wait.Until",
		"expectedResult": ""
	}]
}

export default automatedTestWebsiteSample;
