name: QA Automation Deployment
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{  secrets.QA_AUTOMATION_PRIVATE_KEY }}
          known_hosts: ${{ secrets.QA_AUTOMATION_KNOWN_HOSTS }}

      - name: Run deploy script
        run: ssh azure-qa@40.78.145.27

      - run: cd ../..
      - run: cd /opt
      - run: cd ./qa_automation/qa-automation-tool
      - run: git pull origin main
      - run: echo "Deployment Start"
      - run: /bin/bash deploy.sh
      - run: echo "Deployment completed successfully!"
